site_name: coreproject-seeder
site_description: Seeder soft. for CoreProject
site_author: Moonlit Grace

repo_url: https://github.com/coreproject-moe/coreproject-seeder
edit_uri: https://github.com/coreproject-moe/coreproject-seeder/edit/main/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributor Guide: about/contributing.md
    - License: about/license.md
