name: Test build for various platforms

on:
    push:
        branches:
            - '*'
        tags:
            - '*'
    pull_request:
    workflow_dispatch:

permissions:
    contents: read

jobs:
    linux:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Python 3.12
              uses: actions/setup-python@v2
              with:
                  python-version: 3.12.x

            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                  virtualenvs-create: true
                  virtualenvs-in-project: true

            - name: Install python dependencies
              run: |
                  poetry install

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: '3.22.2'

            - name: Flet Build Linux
              run: |
                  poetry run flet build linux ./src/seeder_flet
